-- =========================================================
-- 世界のひとさじ 調味料22件 登録スクリプト
-- 事前準備:
--   1) アプリで「道満調味料研究所」というニックネームのアカウントを作成
--   2) このSQL全体を Supabase の SQL Editor に貼って実行
-- =========================================================
DO $$
DECLARE owner UUID;
BEGIN
  SELECT id INTO owner FROM public.profiles WHERE nickname = '道満調味料研究所' LIMIT 1;
  IF owner IS NULL THEN
    RAISE EXCEPTION 'ニックネーム「道満調味料研究所」のアカウントが見つかりません。先にアプリで登録してください。';
  END IF;

  DELETE FROM public.condiments WHERE user_id = owner;  -- 二重登録防止（任意）

  INSERT INTO public.condiments
    (name, category, description, origin, recommended_dishes, repeat_rating, purchase_location, taste_profile, image_url, user_id)
  VALUES
  ('みどりのラー油', '辛味', '新潟県小千谷市特産のかぐら南蛮を原料にしたみどり色のラー油です。少し遅れてくるさわやかな辛味が料理の味を引き立てます。きれいなみどり色が料理の色合いを際立たせて美味しく見せます。2020調味料選手権辛味部門最優秀賞・2018審査員特別賞受賞。いつものメニューが変わる、美味しさを引き出す魔法の一滴。', '新潟県', ARRAY['スープ','ラーメン','冷奴','そば・うどん','カプレーゼ','ちょい辛サラダ']::text[], 5, 'オンライン', '{"sweetness": 0, "sourness": 1, "bitterness": 4, "umami": 2, "saltiness": 2, "richness": 3, "aroma": 5}'::jsonb, 'https://mi-ku0816.github.io/sekai-hitosaji/condiments/01_a.jpg', owner),
  ('薫る焦がし醤油', '醤油', 'かつお節や昆布の旨みと焦がし醤油の香ばしい風味が料理の味を上品にひきたてます。瓶の中に短冊状のかごめ昆布が入っており、使うたびに昆布だしが深まります。鍋肌で丁寧に焦がした上品な味わい。製造：北海道函館市。', '北海道', ARRAY['卵かけご飯','納豆','お浸し','焼き魚','ステーキ']::text[], 4, 'オンライン', '{"sweetness": 1, "sourness": 0, "bitterness": 2, "umami": 4, "saltiness": 3, "richness": 2, "aroma": 5}'::jsonb, 'https://mi-ku0816.github.io/sekai-hitosaji/condiments/02_a.jpg', owner),
  ('離宮の食べる七味', 'スパイス', '京都離宮が手がける、食べられる七味唐辛子。国産とうがらし・ゆず・山椒・黒ごま・青のり・生姜を合わせた芳醇な風味。京都の食文化が凝縮された本格派スパイス。製造：京都府京都市。', '京都府', ARRAY['鍋料理','うどん','焼き鳥','天ぷら','お浸し']::text[], 4, '専門店', '{"sweetness": 0, "sourness": 1, "bitterness": 3, "umami": 1, "saltiness": 2, "richness": 1, "aroma": 5}'::jsonb, 'https://mi-ku0816.github.io/sekai-hitosaji/condiments/03_a.jpeg', owner),
  ('心のぽん酢醤油', '醤油', 'ほんとうに美味しいぽん酢醤油を造るため、原材料にこだわりました。埼玉県の国産丸大豆醤油、高知の有機栽培ゆず果汁、愛知のみりん、種子島の粗糖、山梨の甲州味噌、メキシコ産天日塩、静岡の鰹厚削り、日高みついし昆布、大分の干し椎茸、そして戸塚醸造の心の酢。「美味しい！」の笑顔を届けるために造った、心のこもったぽん酢醤油です。', '埼玉県', ARRAY['鍋料理','餃子','冷奴','サラダ','焼き魚']::text[], 4, 'オンライン', '{"sweetness": 2, "sourness": 4, "bitterness": 0, "umami": 3, "saltiness": 3, "richness": 2, "aroma": 3}'::jsonb, 'https://mi-ku0816.github.io/sekai-hitosaji/condiments/04_a.jpg', owner),
  ('生きてる醤油', '醤油', '「生きてる醤油」は何百年の昔に食されていたそのままの醤油を、食卓に届けようとするものです。すべての微生物が生きたままの醤油。古式天然醸造2年熟成醤油もろみから、一番しぼりの雫だけを集めた希少価値のある醤油です。大豆は京都産を使用。製造：京都府綾部市。', '京都府', ARRAY['刺身','卵かけご飯','冷奴','お刺身','お寿司']::text[], 5, '専門店', '{"sweetness": 1, "sourness": 1, "bitterness": 0, "umami": 5, "saltiness": 3, "richness": 4, "aroma": 4}'::jsonb, 'https://mi-ku0816.github.io/sekai-hitosaji/condiments/05_a.jpg', owner),
  ('北海道の鰹節香るだし醤油', 'だし', '北海道丸大豆醤油に鰹節をベースとしただしをブレンド。上品な甘みと豊かな旨みが広がる、まろやかな味わいのだし醤油です。北海道産素材（丸大豆・小麦・鰹節・日高昆布）にこだわった逸品。調味料選手権2023しょうゆ部門最優秀賞受賞。鰹節の旨みひろがる、甘旨仕立てのだし醤油。', '北海道', ARRAY['バター醤油もち','醤油焼きうどん','ズッキーニとツナの和風サラダ','卵かけご飯','冷奴']::text[], 5, 'オンライン', '{"sweetness": 2, "sourness": 0, "bitterness": 0, "umami": 4, "saltiness": 3, "richness": 2, "aroma": 4}'::jsonb, 'https://mi-ku0816.github.io/sekai-hitosaji/condiments/06_a.jpg', owner),
  ('底引きたまり', '醤油', '圧縮や加熱をしていない純生引溜は酵母と乳酸菌にストレスがかかっていません。活きたままの生詰めです。杉桶天然醸造三年半以上の希少品。木桶下部より滴る自然分離の古式たまり。国産丸大豆使用、三重県鈴鹿市製造。', '三重県', ARRAY['刺身','漬け丼','お寿司','冷奴','ステーキ']::text[], 5, '専門店', '{"sweetness": 1, "sourness": 0, "bitterness": 1, "umami": 5, "saltiness": 4, "richness": 5, "aroma": 3}'::jsonb, 'https://mi-ku0816.github.io/sekai-hitosaji/condiments/07_a.jpg', owner),
  ('ひしほ', '醤油', '発酵食文化の栄える金沢大野。ヤマトは1911年創業の醤油味噌屋。「ひしほ醤油」は、香りの良さと豊かな味わいで世界のトップシェフから選ばれている一品です。国産丸大豆・国産小麦使用、加熱殺菌せずミクロフィルターでろ過した生醤油。石川県金沢市製造。', '石川県', ARRAY['冷奴','鯛のあら炊き','スペアリブ','和風ハンバーグ','肉じゃが']::text[], 5, '専門店', '{"sweetness": 1, "sourness": 0, "bitterness": 0, "umami": 4, "saltiness": 3, "richness": 3, "aroma": 5}'::jsonb, 'https://mi-ku0816.github.io/sekai-hitosaji/condiments/08_a.jpeg', owner),
  ('赤ぽん酢', '酢', '赤唐辛子の辛味と花ゆずのさわやかな果汁感を合わせたピリッと辛い柚子こしょう風味のぽん酢です。辛味と酸味のバランスにこだわり、後を引く美味しさに仕上げました。調味料選手権2021鍋部門最優秀賞受賞。花ゆずと赤唐辛子のピリ辛ぽん酢。千葉県野田市製造。', '千葉県', ARRAY['鍋もの','サラダ','冷奴','餃子','焼肉']::text[], 5, 'オンライン', '{"sweetness": 1, "sourness": 4, "bitterness": 1, "umami": 2, "saltiness": 2, "richness": 1, "aroma": 4}'::jsonb, 'https://mi-ku0816.github.io/sekai-hitosaji/condiments/09_a.jpg', owner),
  ('伊達の旨塩', '塩', '牡蠣の養殖が盛んな宮城県石巻市の湾の海水をくみ、誰にもまねできないこだわりの自作の釜を使って、家族二人三脚で丁寧につくられています。魚介の旨みと相性が良い旨みをもつ塩。その名のとおり、旨い塩です。（Solco）', '宮城県', ARRAY['焼き魚','刺身','ステーキ','天ぷら','サラダ']::text[], 4, 'オンライン', '{"sweetness": 0, "sourness": 0, "bitterness": 0, "umami": 3, "saltiness": 4, "richness": 1, "aroma": 2}'::jsonb, 'https://mi-ku0816.github.io/sekai-hitosaji/condiments/10_a.jpeg', owner),
  ('笹川流れの塩', '塩', '新潟県の名勝・天然記念物として知られる海岸「笹川流れ」。その海域の海水を何度もさらしの布に通してアクを取り除きながら、じっくり薪で炊きあげられています。さらにワラのツトに1日置いて、えぐみのない塩が出来上がります。（Solco）', '新潟県', ARRAY['赤身の魚料理','トマト料理','おにぎり','ステーキ','天ぷら']::text[], 4, 'オンライン', '{"sweetness": 0, "sourness": 0, "bitterness": 0, "umami": 2, "saltiness": 4, "richness": 1, "aroma": 2}'::jsonb, 'https://mi-ku0816.github.io/sekai-hitosaji/condiments/11_a.jpeg', owner),
  ('深層海塩ハマネ焼塩', '塩', '伊豆大島の噴火溶岩層（玄武岩）で自然にろ過された地下300mの海水をくみ上げ、2008年から製塩開始。24時間稼働のネット式塩田で天日濃縮後、低温の平釜でじっくり結晶。さらに鍋で手を動かしながら焼いた焼塩は、今まで食べたどの焼塩とも違う、一段突き抜けた気品のあるうまさです。（Solco）', '東京都（伊豆大島）', ARRAY['肉料理','グリル料理','焼き魚','ステーキ','天ぷら']::text[], 5, 'オンライン', '{"sweetness": 0, "sourness": 0, "bitterness": 1, "umami": 2, "saltiness": 4, "richness": 2, "aroma": 3}'::jsonb, 'https://mi-ku0816.github.io/sekai-hitosaji/condiments/12_a.jpeg', owner),
  ('マスターネ。木桶醤油', 'ソース', '直接料理にかけるだけの簡単調味料。マスタードの種を潰さず、木桶で作った酢と醤油、朝倉産のはちみつ、こだわりの砂糖、食塩で作った調味液に漬け込んだ粒マスタード。コッテリした料理にかけるだけで、サッパリとした味に変わります。調味料選手権2023日本の伝統調味料部門最優秀賞。プチプチ食感がくせになる。福岡県朝倉市製造。', '福岡県', ARRAY['野菜和え物','納豆','刺身','豆腐','サラダ','グリル肉']::text[], 5, 'オンライン', '{"sweetness": 2, "sourness": 3, "bitterness": 1, "umami": 3, "saltiness": 2, "richness": 2, "aroma": 4}'::jsonb, 'https://mi-ku0816.github.io/sekai-hitosaji/condiments/13_a.jpg', owner),
  ('いしる', 'タレ', '「いしる」とは魚などの内臓を塩に漬けこんでつくる魚醤です。1〜3年ほど熟成させ、発酵が進むことで旨みが凝縮されます。能登半島のいしるは、秋田の「しょっつる」、四国の「いかなご」と並ぶ日本三大魚醤のひとつ。ベトナムのニョクマムやタイのナンプラーと同じ製法。国産いわし使用、石川県能登町製造。', '石川県', ARRAY['チャーハン','炒め物','カレー','パスタ','鍋料理']::text[], 4, '専門店', '{"sweetness": 0, "sourness": 0, "bitterness": 0, "umami": 5, "saltiness": 5, "richness": 2, "aroma": 4}'::jsonb, 'https://mi-ku0816.github.io/sekai-hitosaji/condiments/14_a.jpg', owner),
  ('トマトバ塩', '塩', '越前の海からとれた職人の塩を焙煎し石臼で挽き、純度高い福井産バジルとトマト・ガーリックを混ぜ込みました。食欲そそる香りと旨味をご堪能ください。調味料選手権2022塩部門最優秀賞受賞。香りと旨味を、ひと振り。福井県丹生郡製造。', '福井県', ARRAY['肉料理','魚料理','天ぷら','卵料理','スープ','サラダ']::text[], 5, 'オンライン', '{"sweetness": 1, "sourness": 1, "bitterness": 1, "umami": 2, "saltiness": 3, "richness": 1, "aroma": 5}'::jsonb, 'https://mi-ku0816.github.io/sekai-hitosaji/condiments/15_a.jpg', owner),
  ('ジンジャーママ しょうが生ふりかけ', 'スパイス', '味噌と鰹節が隠し味。辛みを抑えて食べやすく、お子さまにも人気です。国産しょうがを使用した生ふりかけ。調味料選手権2023ご飯のおとも部門最優秀賞・総合3位受賞。大人も子どもも食べられる、しょうがのふりかけ。愛知県豊川市製造。', '愛知県', ARRAY['ご飯','卵かけご飯','冷奴','麺類の薬味','生姜焼き']::text[], 5, 'オンライン', '{"sweetness": 2, "sourness": 1, "bitterness": 2, "umami": 3, "saltiness": 2, "richness": 1, "aroma": 4}'::jsonb, 'https://mi-ku0816.github.io/sekai-hitosaji/condiments/16_a.png', owner),
  ('卵かけごはんにかける醤油', '醤油', '一本一本に天然昆布がそのまま入っているので、使うたびに昆布のだしが効いて美味しくなります。日本人の朝食の定番をより一層おいしく。熊本県熊本市製造。', '熊本県', ARRAY['卵かけご飯','冷奴','お浸し','刺身','焼き魚']::text[], 4, 'オンライン', '{"sweetness": 3, "sourness": 0, "bitterness": 0, "umami": 4, "saltiness": 3, "richness": 2, "aroma": 3}'::jsonb, 'https://mi-ku0816.github.io/sekai-hitosaji/condiments/17_a.jpeg', owner),
  ('卵に醤油', '醤油', '鰹だしベースの卵かけご飯専用醤油。地元の養鶏農家が「うちの卵がめっちゃうまくなる！」と大絶賛。納豆やおひたしにも。茨城県筑西市製造。', '茨城県', ARRAY['卵かけご飯','納豆','お浸し','冷奴','豆腐料理']::text[], 4, 'オンライン', '{"sweetness": 2, "sourness": 0, "bitterness": 0, "umami": 4, "saltiness": 3, "richness": 2, "aroma": 3}'::jsonb, 'https://mi-ku0816.github.io/sekai-hitosaji/condiments/18_a.jpeg', owner),
  ('きくらげラー油', '辛味', '愛知県豊川市で愛情込めて育てられた、無農薬栽培の肉厚プリプリのきくらげをふんだんに使用。味がしっかりとしみ込んでいてニンニクのアクセントが効いてます。ピリ辛ラー油味に仕上げたきくらげの佃煮。福島県郡山市製造。', '福島県', ARRAY['ごはん','卵かけご飯','チャーハン','炒め物','冷奴']::text[], 4, 'オンライン', '{"sweetness": 1, "sourness": 1, "bitterness": 2, "umami": 4, "saltiness": 3, "richness": 3, "aroma": 3}'::jsonb, 'https://mi-ku0816.github.io/sekai-hitosaji/condiments/19_a.jpeg', owner),
  ('しろたまり', '醤油', '奥三河足助大多賀の豊かな自然環境の中、木桶で仕込んだ逸品。厳選した国産小麦と伝統海塩「海の精」を天然水で仕込み、じっくりと熟成させました。愛知県産小麦100%の調味料。愛知県碧南市製造。', '愛知県', ARRAY['卵焼き','お吸い物','ホワイトソース','冷奴','お浸し']::text[], 4, '専門店', '{"sweetness": 4, "sourness": 0, "bitterness": 0, "umami": 3, "saltiness": 2, "richness": 2, "aroma": 3}'::jsonb, 'https://mi-ku0816.github.io/sekai-hitosaji/condiments/20_a.jpeg', owner),
  ('玉子ごはん専用昆布醤油', '醤油', 'ご飯や玉子の持つ甘みを活かす優しい甘味こそが二杯目も美味しく食べれるポイント。甘さの質がポイントの、玉子ごはん専用に設計された昆布醤油。一杯目が美味しいのは当たり前。二杯目がうまくてこそ本物。熊本県熊本市製造。', '熊本県', ARRAY['玉子ごはん','卵かけご飯','冷奴','お浸し','豆腐料理']::text[], 4, 'オンライン', '{"sweetness": 4, "sourness": 0, "bitterness": 0, "umami": 4, "saltiness": 2, "richness": 2, "aroma": 3}'::jsonb, 'https://mi-ku0816.github.io/sekai-hitosaji/condiments/21_a.jpg', owner),
  ('みんなのニラ醤油', '醤油', '大分特産のニラを丸ごと新鮮なまま特製オリジナル醤油に漬け込んだ万能味変調味料。専用の特製醤油にニラの旨味を凝縮した逸品です。大分県産ニラにこだわった産地指定の一品。ニラで泣ける！大分県大分市製造。', '大分県', ARRAY['ご飯','卵かけごはん','納豆','焼肉','パスタ','チャーハン','刺身','鍋の薬味']::text[], 4, 'オンライン', '{"sweetness": 1, "sourness": 0, "bitterness": 1, "umami": 4, "saltiness": 3, "richness": 2, "aroma": 5}'::jsonb, 'https://mi-ku0816.github.io/sekai-hitosaji/condiments/22_a.jpg', owner);
END $$;
